### PR TITLE
fix(find): fixed id generator so that id starts with a letter Fix #94

### LINKED ISSUE #94: Elements find function sometimes fails due to invalid ID in selector
**Describe the bug**
If selector for find starts with `>`, then ID for current element is generated. There's an issue where this random ID will start with a number which will cause the querySelectorAll to fail.

**To Reproduce**
1. Use @El or .find with `>` at the beginning of selector
2. Refresh the component (possibly a few times, since it's a random behaviour)

**Expected behavior**
Find doesn't fail and finds element with specified selector

### PR DESCRIPTION
**Pull request by jakublamprecht**
fix(find): fixed id generator so that id starts with a letter and updated yarn.lock Fix #94

### CODE REVIEW

File: src/dom/element.js [hunk 1]
```diff
@@ -494,7 +494,7 @@ class Element {
         var hadId = true;
         if (!node.id) {
           hadId = false;
-          node.id = Math.random().toString(36).substr(2, 9);
+          node.id = 'strudel-' + Math.random().toString(36).substr(2, 9);
```
Comment (mateuszluczak) [inline src/dom/element.js]: U could use string interpolation here, but I guess this is fine too 🤷‍♂
